### ISSUE TITLE
AssertionError: Bottleneck_BatchNorm/batchnorm_1/add_1 is not in graph

### ISSUE THREAD

**Issue by futureflsl** [riotu-lab/deepstream-facenet#11]
when converting pb file to onnx use below command instead: python -m tf2onnx.convert --input facenet.pb --inputs input_1:0[1,160,160,3] --inputs-as-nchw input_1:0 --outputs
but error occurrd like this:
Traceback (most recent call last):
  File "/home/fut/miniconda3/envs/fut/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fut/miniconda3/envs/fut/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fut/miniconda3/envs/fut/lib/python3.7/site-packages/tf2onnx/convert.py", line 467, in <module>
    main()
  File "/home/fut/miniconda3/envs/fut/lib/python3.7/site-packages/tf2onnx/convert.py", line 205, in main
    graph_def, inputs, outputs = tf_loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/home/fut/miniconda3/envs/fut/lib/python3.7/site-packages/tf2onnx/tf_loader.py", line 202, in from_graphdef
    frozen_graph = freeze_session(sess, input_names=input_names, output_names=output_names)
  File "/home/fut/miniconda3/envs/fut/lib/python3.7/site-packages/tf2onnx/tf_loader.py", line 167, in freeze_session
    graph_def = convert_variables_to_constants(sess, graph_def, output_node_names)
  File "/home/fut/miniconda3/envs/fut/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/fut/miniconda3/envs/fut/lib/python3.7/site-packages/tensorflow/python/framework/graph_util_impl.py", line 270, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/home/fut/miniconda3/envs/fut/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/fut/miniconda3/envs/fut/lib/python3.7/site-packages/tensorflow/python/framework/graph_util_impl.py", line 182, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/home/fut/miniconda3/envs/fut/lib/python3.7/site-packages/tensorflow/python/framework/graph_util_impl.py", line 137, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: Bottleneck_BatchNorm/batchnorm_1/add_1 is not in graph

**Comment by xya22er** [comment]
I think you missed  to write output name in the command
